{
 "title": "AirPro New",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "timezone", "query": "Europe/Moscow" }
  ]
 },
 "panels": [
  {
   "title": "AQI (US)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "query": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    aqi_us as \"Air Quality\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "rawQuery": "SELECT\n    toTimeZone(timestamp, 'Europe/Moscow') as t,\n    aqi_us as \"Air Quality\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime(1712943959)\n    AND toDateTime(1712954759)\nORDER BY timestamp",
     "round": "0s"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "AQI(US)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "query": "SELECT avg(aqi_us) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1\n",
     "rawQuery": "SELECT avg(aqi_us) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1",
     "round": "0s"
    }
   ]
  },
  {
   "title": "CO2 (ppm)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT avg(aqi_us) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1\n",
     "query": "SELECT avg(co2) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1\n",
     "rawQuery": "SELECT avg(co2) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT avg(aqi_us) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1\n",
     "query": "SELECT avg(temperature) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1\n",
     "rawQuery": "SELECT avg(temperature) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Humidity (%RH)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT avg(aqi_us) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1\n",
     "query": "SELECT avg(humidity) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1\n",
     "rawQuery": "SELECT avg(humidity) as home\nFROM airpro\nGROUP BY toStartOfFiveMinute(timestamp)\nORDER BY toStartOfFiveMinute(timestamp) DESC\nLIMIT 1",
     "round": "0s"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CO2 (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "query": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    co2 as \"CO2\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "rawQuery": "SELECT\n    toTimeZone(timestamp, 'Europe/Moscow') as t,\n    co2 as \"CO2\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime(1712869778)\n    AND toDateTime(1712956178)\nORDER BY timestamp",
     "round": "0s"
    }
   ]
  },
  {
   "title": "PM (μg/m3)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    co2 as \"CO2\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "query": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    pm1 as \"PM 1\",\n    pm2_5 as \"PM 2.5\",\n    pm10  as \"PM 10\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "rawQuery": "SELECT\n    toTimeZone(timestamp, 'Europe/Moscow') as t,\n    pm1 as \"PM 1\",\n    pm2_5 as \"PM 2.5\",\n    pm10  as \"PM 10\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime(1712870145)\n    AND toDateTime(1712956545)\nORDER BY timestamp",
     "round": "0s"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    co2 as \"CO2\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "query": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    temperature as Temperature\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "rawQuery": "SELECT\n    toTimeZone(timestamp, 'Europe/Moscow') as t,\n    temperature as Temperature\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime(1712870433)\n    AND toDateTime(1712956833)\nORDER BY timestamp",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Humidity (%RH)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    co2 as \"CO2\"\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "query": "SELECT\n    toTimeZone(timestamp, '$timezone') as t,\n    humidity as Humidity\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime($from)\n    AND toDateTime($to)\nORDER BY timestamp",
     "rawQuery": "SELECT\n    toTimeZone(timestamp, 'Europe/Moscow') as t,\n    humidity as Humidity\nFROM airpro\nWHERE\n    timestamp BETWEEN toDateTime(1712870481)\n    AND toDateTime(1712956881)\nORDER BY timestamp",
     "round": "0s"
    }
   ]
  }
 ]
}