
###
GET http://127.0.0.1:9999/api/v1/settings
Content-Type: application/json


###
GET http://127.0.0.1:9999/api/v1/files
Content-Type: application/json

###
GET http://127.0.0.1:9999/api/v1/load-modified
Content-Type: application/json

###
GET http://127.0.0.1:9999/api/v1/load-all
Content-Type: application/json
